---
version: "3.8"
services:
  #postgres db
  db:
    image: mysql/mysql-server:8.0.32-1.2.11-server
    container_name: mysql_container
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_RANDOM_ROOT_PASSWORD=false
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - backbone

  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2
    container_name: php_container
    restart: unless-stopped
    tty: true
    ports:
      - 9000:9000
    expose:
      - "9000"
    volumes:
      - ./php-ini:/usr/local/etc/php/custom.d
      - .:/var/www/app/
    networks:
      - backbone

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app/
    environment:
      - NGINX_PORT=80
    depends_on:
      - php
    networks:
      - backbone
  

#network
networks:
  backbone:
    driver: bridge